apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: coconut-backend
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: coconut-finance
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "backend"
        effect: "NoSchedule"
      containers:
      - name: backend
        image: 992382629018.dkr.ecr.ap-northeast-2.amazonaws.com/castlehoo/backend:112
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: CLOUD_DB_URL
          valueFrom:
            secretKeyRef:
              name: db-redis-secret
              key: CLOUD_DB_URL
        - name: CLOUD_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-redis-secret
              key: CLOUD_DB_USERNAME
        - name: CLOUD_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-redis-secret
              key: CLOUD_DB_PASSWORD
        - name: ONPREM_DB_URL
          valueFrom:
            secretKeyRef:
              name: db-redis-secret
              key: ONPREM_DB_URL
        - name: ONPREM_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-redis-secret
              key: ONPREM_DB_USERNAME
        - name: ONPREM_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-redis-secret
              key: ONPREM_DB_PASSWORD
        - name: ONPREM_READ_DB_URL
          valueFrom:
            secretKeyRef:
              name: db-redis-secret
              key: ONPREM_READ_DB_URL
