# service.yaml 
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: coconut-backend
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: coconut-finance
spec:
  type: LoadBalancer  # ClusterIP에서 LoadBalancer로 변경
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend
